[tools]
go = "1.22.5"
task = "3.38.0"
goreleaser = "2.1.0"
act = "0.2.65"
"go:honnef.co/go/tools/cmd/staticcheck" = "0.4.7"
"go:github.com/psampaz/go-mod-outdated" = "0.9.0"
"go:oss.terrastruct.com/d2" = "0.6.6"
